import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 5,
  tables: [
    tableSchema({
      name: 'products',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'category_id', type: 'string' },
        { name: 'base_price', type: 'number' },
        { name: 'sku', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'is_available', type: 'boolean' },
        { name: 'is_gst_free', type: 'boolean' },
        { name: 'sort_order', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'modifier_groups',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'display_name', type: 'string', isOptional: true },
        { name: 'selection_type', type: 'string' },
        { name: 'min_selections', type: 'number' },
        { name: 'max_selections', type: 'number' },
        { name: 'sort_order', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'modifiers',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'modifier_group_id', type: 'string' },
        { name: 'price_adjustment', type: 'number' },
        { name: 'is_default', type: 'boolean' },
        { name: 'is_available', type: 'boolean' },
        { name: 'sort_order', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'product_modifier_groups',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'product_id', type: 'string' },
        { name: 'modifier_group_id', type: 'string' },
        { name: 'sort_order', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'colour', type: 'string', isOptional: true },
        { name: 'icon', type: 'string', isOptional: true },
        { name: 'sort_order', type: 'number' },
        { name: 'parent_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'loyalty_tier', type: 'string', isOptional: true },
        { name: 'loyalty_balance', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'order_number', type: 'string' },
        { name: 'order_type', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'table_number', type: 'string', isOptional: true },
        { name: 'customer_id', type: 'string', isOptional: true },
        { name: 'staff_id', type: 'string' },
        { name: 'terminal_id', type: 'string' },
        { name: 'subtotal', type: 'number' },
        { name: 'gst', type: 'number' },
        { name: 'total', type: 'number' },
        { name: 'discount_amount', type: 'number' },
        { name: 'discount_type', type: 'string', isOptional: true },
        { name: 'discount_value', type: 'number' },
        { name: 'discount_reason', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'held_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'order_items',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'order_id', type: 'string' },
        { name: 'product_id', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit_price', type: 'number' },
        { name: 'modifiers_json', type: 'string', isOptional: true },
        { name: 'line_total', type: 'number' },
        { name: 'discount_amount', type: 'number' },
        { name: 'discount_type', type: 'string', isOptional: true },
        { name: 'discount_value', type: 'number' },
        { name: 'discount_reason', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'payments',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'order_id', type: 'string' },
        { name: 'method', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'tip_amount', type: 'number' },
        { name: 'reference', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'shifts',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'staff_id', type: 'string' },
        { name: 'terminal_id', type: 'string' },
        { name: 'opened_at', type: 'number' },
        { name: 'closed_at', type: 'number', isOptional: true },
        { name: 'opening_float', type: 'number' },
        { name: 'closing_float', type: 'number', isOptional: true },
        { name: 'expected_cash', type: 'number', isOptional: true },
        { name: 'actual_cash', type: 'number', isOptional: true },
        { name: 'variance', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'staff',
      columns: [
        { name: 'server_id', type: 'string' },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'role', type: 'string' },
        { name: 'pin_hash', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'permissions_json', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
